### ISSUE TITLE
Build credits page

### ISSUE THREAD

**Issue by AvielCo** [AvielCo/SmartScript#22]
- [ ] Build an abstract developer card (1 in image)
- [ ]  Duplicate developer card 3 times with developers information (2)
- [ ] Few words on the developers (3)

![1](https://user-images.githubusercontent.com/38301471/109764405-2c4ab280-7bfc-11eb-9518-5477da849302.png)

**Comment by SoloNoah** [comment]
Just letting you guys know that I already did this. Its on my laptop and pretty much done. I just didn't post it. I showed you the progress like a month ago.
@EmiliaZorin If u want the code and go on from there lemme know.
