### ISSUE TITLE
[FRONT] Profile search bar + list

### ISSUE THREAD

**Issue by SoloNoah** [AvielCo/SmartScript#48]
- [x] add search bar 
- [x] add results list
- [x] load user history and load list

**Comment by AvielCo** [comment]
See changes in History model when working on this issue

**Comment by SoloNoah** [comment]
basically done, right? just the css stuff + that search results issue we talked about earlier left to be done. @AvielCo

**Comment by AvielCo** [comment]
Just need to merge backend profile, ill do it later

**Comment by SoloNoah** [comment]
no pressure. just wanted to make sure i'm not mistaken. we can do it together on saturday or sunday when we meet
