### ISSUE TITLE
[FRONT] enhancing css in this section

### ISSUE THREAD

**Issue by SoloNoah** [AvielCo/SmartScript#52]
its a bit strange that the style is applied with `span`. it appears in Material-UI's documents but maybe there is a better way

https://github.com/AvielCo/SmartScript/blob/ad8c9b91ec82938cdce5a82490bd4be66011b76a/client/src/components/Buttons/InputButton.css#L1-L11

**Comment by AvielCo** [comment]
Theres no need to.

**Comment by AvielCo** [comment]
Now can use the access token to upload and predict images. (only logged in users can do it)
