### ISSUE TITLE
[FRONT] Error handling in every page and section

### ISSUE THREAD

**Issue by AvielCo** [AvielCo/SmartScript#56]
- [x] Create error handling in login page when user is not found: "Username or password are incorrect."
- [x] in register page when: 
1. email is already exists: "Email is already exists"
2. username is already exists: "Username is already exists"

- [x] handle 500 (InternalServerError): show "Unexpected error" when 500 occurred.
- [x] handle 401 (UnauthorizedError): show 404 page

**Comment by SoloNoah** [comment]
related to #41

**Comment by AvielCo** [comment]
Done all 4 in Register and Login page (see branch issue56)

**Comment by AvielCo** [comment]
Done
